// <auto-generated />
using System;
using AP8POSecretary.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AP8POSecretary.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("AP8POSecretary.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CommitmentRate")
                        .HasColumnType("REAL");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("WholeName")
                        .HasColumnType("TEXT");

                    b.Property<double>("WorkingPoints")
                        .HasColumnType("REAL");

                    b.Property<double>("WorkingPointsWithEng")
                        .HasColumnType("REAL");

                    b.Property<bool>("isDoctorant")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Employee", "Secretary");
                });

            modelBuilder.Entity("AP8POSecretary.Domain.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<int>("SemesterType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Shortcut")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudyType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudyYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Group", "Secretary");
                });

            modelBuilder.Entity("AP8POSecretary.Domain.Entities.GroupSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("SubjectId");

                    b.ToTable("GroupSubject", "Secretary");
                });

            modelBuilder.Entity("AP8POSecretary.Domain.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Credit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Language")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LectureCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PractiseCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeminareCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Shortcut")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeeksCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Subject", "Secretary");
                });

            modelBuilder.Entity("AP8POSecretary.Domain.Entities.WorkingLabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EmploymentPoints")
                        .HasColumnType("REAL");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoursCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SubjectId");

                    b.ToTable("WorkingLabel", "Secretary");
                });

            modelBuilder.Entity("AP8POSecretary.Domain.Entities.WorkingPointsWeight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkingWeightTypes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WorkingPointsWeight", "Secretary");
                });

            modelBuilder.Entity("AP8POSecretary.Domain.Entities.GroupSubject", b =>
                {
                    b.HasOne("AP8POSecretary.Domain.Entities.Group", "Group")
                        .WithMany("GroupSubjects")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AP8POSecretary.Domain.Entities.Subject", "Subject")
                        .WithMany("GroupSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("AP8POSecretary.Domain.Entities.WorkingLabel", b =>
                {
                    b.HasOne("AP8POSecretary.Domain.Entities.Employee", "Employee")
                        .WithMany("WorkingLabels")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AP8POSecretary.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Employee");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("AP8POSecretary.Domain.Entities.Employee", b =>
                {
                    b.Navigation("WorkingLabels");
                });

            modelBuilder.Entity("AP8POSecretary.Domain.Entities.Group", b =>
                {
                    b.Navigation("GroupSubjects");
                });

            modelBuilder.Entity("AP8POSecretary.Domain.Entities.Subject", b =>
                {
                    b.Navigation("GroupSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
